// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conductor_service.proto

/*
Package conductor is a generated protocol buffer package.

It is generated from these files:
	conductor_service.proto

It has these top-level messages:
*/
package conductor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConductorService service

type ConductorServiceClient interface {
}

type conductorServiceClient struct {
	cc *grpc.ClientConn
}

func NewConductorServiceClient(cc *grpc.ClientConn) ConductorServiceClient {
	return &conductorServiceClient{cc}
}

// Server API for ConductorService service

type ConductorServiceServer interface {
}

func RegisterConductorServiceServer(s *grpc.Server, srv ConductorServiceServer) {
	s.RegisterService(&_ConductorService_serviceDesc, srv)
}

var _ConductorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conductor.ConductorService",
	HandlerType: (*ConductorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "conductor_service.proto",
}

func init() { proto.RegisterFile("conductor_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0xcf, 0x4b,
	0x29, 0x4d, 0x2e, 0xc9, 0x2f, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x4b, 0x18, 0x09, 0x71, 0x09, 0x38, 0xc3, 0x38, 0xc1, 0x10,
	0x45, 0x4e, 0x25, 0x5c, 0x4a, 0xc9, 0xf9, 0xb9, 0x7a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0x7a,
	0x25, 0x45, 0x99, 0x39, 0x39, 0x99, 0x89, 0x79, 0xba, 0xa9, 0x15, 0x89, 0xb9, 0x05, 0x39, 0xa9,
	0xc5, 0x10, 0x43, 0x9c, 0x44, 0xd1, 0xf5, 0x05, 0x80, 0x84, 0x03, 0x18, 0xa3, 0x4c, 0xd3, 0x33,
	0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x21, 0x66, 0xe8, 0x63, 0x98, 0xa1, 0x5f,
	0x94, 0x98, 0x99, 0x93, 0x5e, 0x9a, 0xa7, 0x0f, 0x77, 0x49, 0x12, 0x1b, 0xd8, 0x58, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x2a, 0x09, 0xa1, 0xb6, 0x00, 0x00, 0x00,
}
